# Use new container infrastructure to enable caching
dist: trusty
sudo: false

language: haskell

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.cabal

# Ensure necessary system libraries are present
addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc' # PPA of Haskell packages
    packages:
      - libgmp-dev           # required by cabal
      - cabal-install-2.0    # required by GHC 8.x

ghc:
  - "8.4"

git:
  depth: 5


before_install:
  # LLVM
  - echo 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main' >> /etc/apt/sources.list
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - apt-get update
  
  
install:
  # Build dependencies
  - apt-get install llvm-6.0 llvm-6.0-dev llvm-6.0-runtime libllvm6.0
  - apt-get install -f
  - cabal new-configure

script:
# Build the package, its tests, and its docs and run the tests
- cabal new-test language-hawk
