# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: haskell

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.cabal

# Ensure necessary system libraries are present
addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc' # PPA of Haskell packages
    packages:
      - libgmp-dev           # required by cabal
      - cabal-install-2.0    # required by GHC 8.x

ghc:
  - "8.4"

git:
  depth: 5


install:
# Build dependencies
- cabal new-configure

script:
# Build the package, its tests, and its docs and run the tests
- cabal new-test language-hawk
