# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.


name: hawk
maintainer: Gabriel Anderson
synopsis: Hawk programming language
description: Close to the metal with a modern typesystem
github: andgate/hawk
category: Compilers
version: '0.0.0'
license: MIT

build-tools:
  - alex

extra-source-files:
  - CHANGELOG.md
  - LICENSE.md
  - package.yaml
  - README.md
  - stack.yaml
  - src/Language/Hawk/Parse/Lexer.x

ghc-options: 
  - -Wall
  - -fno-warn-name-shadowing
  - -fno-warn-unused-binds
  - -fno-warn-unused-matches
  - -fno-warn-unused-do-bind
  - -fno-warn-orphans


executables:
  hkc:
    source-dirs: executable
    main: Main.hs
    dependencies:
      - base
      - hawk
      - optparse-applicative
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

library:
  source-dirs: src
  dependencies:
    - ansi-wl-pprint
    - array
    - base
    - binary
    - bytestring
    - conduit-combinators
    - containers
    - data-default-class
    - directory
    - Earley
    - edit-distance
    - exceptions
    - filepath
    - ghc-prim
    - lens
    - logging-effect
    - mmorph
    - monad-control
    - monad-logger
    - mono-traversable
    - mtl
    - persistent
    - persistent-sqlite
    - persistent-template
    - primitive
    - resourcet
    - safe
    - streaming-commons
    - text
    - text-format
    - these
    - time
    - transformers
    - transformers-base
    - utf8-string
    - vector

  exposed-modules:      
    - Language.Hawk.Compile
    - Language.Hawk.Compile.Config
    - Language.Hawk.Compile.Error
    - Language.Hawk.Compile.Flags
    - Language.Hawk.Compile.Message
    - Language.Hawk.Compile.Monad
    - Language.Hawk.Compile.Options
    - Language.Hawk.Compile.Package
    - Language.Hawk.Compile.PhaseStatus
    - Language.Hawk.Compile.Source
    - Language.Hawk.Compile.State

    - Language.Hawk.Data.Bag

    - Language.Hawk.Cache
    - Language.Hawk.Cache.Item
    - Language.Hawk.Cache.Janitor
    - Language.Hawk.Cache.Model
    - Language.Hawk.Cache.Module
    - Language.Hawk.Cache.Package
    - Language.Hawk.Cache.Types

    - Language.Hawk.DepExpansion

    - Language.Hawk.NameCheck.Message
    - Language.Hawk.Namespace
    
    - Language.Hawk.Parse
    - Language.Hawk.Parse.Document
    - Language.Hawk.Parse.Grammar
    - Language.Hawk.Parse.Helpers
    - Language.Hawk.Parse.Lexer
    - Language.Hawk.Parse.Lexer.Catalog
    - Language.Hawk.Parse.Lexer.Layout
    - Language.Hawk.Parse.Lexer.Token
    - Language.Hawk.Parse.Message

    - Language.Hawk.Report.Error
    - Language.Hawk.Report.Helpers
    - Language.Hawk.Report.Info
    - Language.Hawk.Report.Region
    - Language.Hawk.Report.Report
    - Language.Hawk.Report.Result
    - Language.Hawk.Report.SrcLoc
    - Language.Hawk.Report.Warning

    - Language.Hawk.Syntax
    - Language.Hawk.Syntax.Pass
    - Language.Hawk.Syntax.Prim

    - Language.Hawk.TypeCheck
    - Language.Hawk.TypeCheck.Context
    - Language.Hawk.TypeCheck.NameGen


tests:
  spec:
    source-dirs: test-suite
    main: Spec.hs
    dependencies:
      - base
      - hawk
      - tasty
      - tasty-hspec
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

#  doctest:
#    source-dirs: test-suite
#    main: DocTest.hs
#    dependencies:
#      - base
#      - doctest
#      - Glob
#    ghc-options:
#      - -rtsopts
#      - -threaded
#      - -with-rtsopts=-N

  hlint:
    source-dirs: test-suite
    main: HLint.hs
    dependencies:
      - base
      - hlint
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    

benchmarks:
  criterion:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
      - base
      - hawk
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
