# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.


name: hawk
maintainer: Gabriel Anderson
synopsis: Hawk programming language
description: Close to the metal with a modern typesystem
github: andgate/hawk
category: Compilers
version: '0.0.0'
license: MIT

build-tools:
  - alex

extra-source-files:
  - CHANGELOG.md
  - LICENSE.md
  - package.yaml
  - README.md
  - stack.yaml
  - src/Language/Hawk/Parse/Lexer.x

ghc-options: 
  - -Wall
  - -fno-warn-name-shadowing
  - -fno-warn-unused-binds
  - -fno-warn-unused-matches
  - -fno-warn-unused-do-bind
  - -fno-warn-orphans


executables:
  hkc:
    source-dirs: executable
    main: Main.hs
    dependencies:
      - base
      - hawk
      - optparse-applicative
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

library:
  source-dirs: src
  dependencies:
    - array
    - base
    - binary
    - bytestring
    - containers
    - data-default-class
    - data-default-instances-text
    - directory
    - edit-distance
    - exceptions
    - filepath
    - ghc-prim
    - lens
    - lifted-base
    - lifted-async
    - logging-effect
    - megaparsec
    - mmorph
    - monad-control
    - monad-logger
    - mono-traversable
    - mtl
    - primitive
    - resourcet
    - safe
    - streaming-commons
    - text
    - text-format
    - these
    - time
    - transformers
    - transformers-base
    - utf8-string
    - vector
    - wl-pprint-text

  exposed-modules:      
    - Language.Hawk.Compile
    - Language.Hawk.Compile.Config
    - Language.Hawk.Compile.Error
    - Language.Hawk.Compile.Flags
    - Language.Hawk.Compile.Message
    - Language.Hawk.Compile.Monad
    - Language.Hawk.Compile.Options
    - Language.Hawk.Compile.PhaseStatus
    - Language.Hawk.Compile.State

    - Language.Hawk.DepExpansion

    - Language.Hawk.Load
    - Language.Hawk.Load.Message
    - Language.Hawk.Load.Error

    - Language.Hawk.NameCheck.Message
    - Language.Hawk.Namespace
    
    - Language.Hawk.Parse
    - Language.Hawk.Parse.Error
    - Language.Hawk.Parse.Helpers
    - Language.Hawk.Parse.Lexer
    - Language.Hawk.Parse.Lexer.Layout
    - Language.Hawk.Parse.Lexer.Token
    - Language.Hawk.Parse.Message
    - Language.Hawk.Parse.Module

    - Language.Hawk.Syntax
    - Language.Hawk.Syntax.Pass
    - Language.Hawk.Syntax.Prim
    - Language.Hawk.Syntax.Location

    - Language.Hawk.TypeCheck
    - Language.Hawk.TypeCheck.Context
    - Language.Hawk.TypeCheck.NameGen

    ## Extra, possibly seperate packages or upstream merges
    - Data.Bag
    - Control.Monad.Chronicle.Extra

tests:
  spec:
    source-dirs: test-suite
    main: Spec.hs
    dependencies:
      - base
      - data-default-class
      - hawk
      - tasty
      - tasty-hspec
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

#  doctest:
#    source-dirs: test-suite
#    main: DocTest.hs
#    dependencies:
#      - base
#      - doctest
#      - Glob
#    ghc-options:
#      - -rtsopts
#      - -threaded
#      - -with-rtsopts=-N

#  hlint:
#    source-dirs: test-suite
#    main: HLint.hs
#    dependencies:
#      - base
#      - hlint
#    ghc-options:
#      - -rtsopts
#      - -threaded
#      - -with-rtsopts=-N
    

benchmarks:
  criterion:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
      - base
      - hawk
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
