# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.


name: hawk
maintainer: Gabriel Anderson
synopsis: Hawk programming language
description: Linear Typed Purely Functional Systems Language
github: andgate/hawk
category: Compilers
version: '0.0.0'
license: MIT

build-tools:
  - alex

extra-source-files:
  - CHANGELOG.md
  - LICENSE.md
  - package.yaml
  - README.md
  - stack.yaml
  - src/Language/Hawk/Lex.x

ghc-options: 
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -fno-warn-name-shadowing
  - -fno-warn-unused-binds
  - -fno-warn-unused-matches
  - -fno-warn-unused-do-bind
  - -fno-warn-orphans


executables:
  hkc:
    source-dirs: executable
    main: Main.hs
    dependencies:
      - base
      - hawk
      - optparse-applicative
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wmissing-import-lists

library:
  source-dirs: src
  dependencies:
    - aeson
    - array
    - base
    - binary
    - bound
    - bytes
    - bytestring
    - containers
    - data-default-class
    - data-default-instances-text
    - deriving-compat
    - directory
    - Earley
    - edit-distance
    - either
    - exceptions
    - extra
    - filepath
    - ghc-prim
    - lens
    - lifted-base
    - lifted-async
    - logging-effect
    - llvm-hs
    - llvm-hs-pure
    - llvm-hs-pretty
    - mmorph
    - monad-control
    - monad-logger
    - monad-gen
    - mono-traversable
    - mtl
    - primitive
    - reducers
    - resourcet
    - safe
    - streaming-commons
    - text
    - text-format
    - these
    - time
    - transformers
    - transformers-base
    - unbound-generics
    - unordered-containers
    - utf8-string
    - vector
    - wl-pprint-text
    - yaml

  exposed-modules:
    - Language.CPS.ClosureConv
    - Language.CPS.LambdaLift
    - Language.CPS.Syntax

    - Language.CPS.Target.LLVM
    - Language.CPS.Target.LLVM.IR
    - Language.CPS.Target.LLVM.Module
    - Language.CPS.Target.LLVM.Instruction

    - Language.Hawk.Compile
    - Language.Hawk.Compile.Config
    - Language.Hawk.Compile.Error
    - Language.Hawk.Compile.Message
    - Language.Hawk.Compile.Monad

    - Language.Hawk.KindsCheck
    - Language.Hawk.KindsCheck.Environment
    - Language.Hawk.KindsCheck.Error
    - Language.Hawk.KindsCheck.Message
    - Language.Hawk.KindsCheck.State

    - Language.Hawk.Lex
    - Language.Hawk.Lex.Error
    - Language.Hawk.Lex.Format
    - Language.Hawk.Lex.Message
    - Language.Hawk.Lex.Result
    - Language.Hawk.Lex.State
    - Language.Hawk.Lex.Token

    - Language.Hawk.LinearCheck
    - Language.Hawk.LinearCheck.Error
    - Language.Hawk.LinearCheck.GlobalEnvironment
    - Language.Hawk.LinearCheck.LocalEnvironment
    - Language.Hawk.LinearCheck.Message
    - Language.Hawk.LinearCheck.State

    - Language.Hawk.Load
    - Language.Hawk.Load.Message
    - Language.Hawk.Load.Error
    - Language.Hawk.Load.Result

    - Language.Hawk.NameCheck
    - Language.Hawk.NameCheck.Environment
    - Language.Hawk.NameCheck.Error
    - Language.Hawk.NameCheck.State

    - Language.Hawk.NameGen
    
    - Language.Hawk.Parse
    - Language.Hawk.Parse.Error
    - Language.Hawk.Parse.Grammar
    - Language.Hawk.Parse.Helpers
    - Language.Hawk.Parse.Message

    - Language.Hawk.Syntax
    - Language.Hawk.Syntax.Expression
    - Language.Hawk.Syntax.Fixity
    - Language.Hawk.Syntax.Foreign
    - Language.Hawk.Syntax.Function
    - Language.Hawk.Syntax.Image
    - Language.Hawk.Syntax.Location
    - Language.Hawk.Syntax.Pattern
    - Language.Hawk.Syntax.Prim
    - Language.Hawk.Syntax.Signature
    - Language.Hawk.Syntax.Type
    - Language.Hawk.Syntax.TypeAlias
    - Language.Hawk.Syntax.TypeS

    - Language.Hawk.Target.CPS

    - Language.Hawk.TypeCheck
    - Language.Hawk.TypeCheck.Assumption
    - Language.Hawk.TypeCheck.Constraint
    - Language.Hawk.TypeCheck.Environment
    - Language.Hawk.TypeCheck.Error
    - Language.Hawk.TypeCheck.State
    - Language.Hawk.TypeCheck.Substitution

    ## Extra, possibly seperate packages or upstream merges
    - Data.Bag
    - Control.Monad.Chronicle.Extra

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - data-default-class
      - hawk
      - hspec
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

