# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.


name: hawk
maintainer: Gabriel Anderson
synopsis: Hawk programming language
description: Linear Typed Purely Functional Systems Language
github: andgate/hawk
category: Compilers
version: '0.0.0'
license: MIT

build-tools:
  - alex

extra-source-files:
  - CHANGELOG.md
  - LICENSE.md
  - package.yaml
  - README.md
  - stack.yaml
  - src/Language/Hawk/Parse/Lex.x

ghc-options: 
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -fno-warn-name-shadowing
  - -fno-warn-unused-binds
  - -fno-warn-unused-matches
  - -fno-warn-unused-do-bind
  - -fno-warn-orphans


executables:
  hkc:
    source-dirs: executable
    main: Main.hs
    dependencies:
      - base
      - hawk
      - optparse-applicative
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wmissing-import-lists

library:
  source-dirs: src
  dependencies:
    - array
    - base
    - binary
    - bound
    - bytes
    - bytestring
    - containers
    - data-default-class
    - data-default-instances-text
    - deriving-compat
    - directory
    - Earley
    - edit-distance
    - either
    - exceptions
    - filepath
    - ghc-prim
    - lens
    - lifted-base
    - lifted-async
    - logging-effect
    - llvm-hs
    - llvm-hs-pure
    - mmorph
    - monad-control
    - monad-logger
    - mono-traversable
    - mtl
    - primitive
    - reducers
    - resourcet
    - safe
    - streaming-commons
    - text
    - text-format
    - these
    - time
    - transformers
    - transformers-base
    - unbound-generics
    - utf8-string
    - vector
    - wl-pprint-text

  exposed-modules:
    - Language.Hawk.Compile
    - Language.Hawk.Compile.Config
    - Language.Hawk.Compile.Error
    - Language.Hawk.Compile.Flags
    - Language.Hawk.Compile.Message
    - Language.Hawk.Compile.Monad
    - Language.Hawk.Compile.Options
    - Language.Hawk.Compile.PhaseStatus
    - Language.Hawk.Compile.State

    - Language.Hawk.Eval

    - Language.Hawk.Load
    - Language.Hawk.Load.Message
    - Language.Hawk.Load.Error

    - Language.Hawk.NameCheck
    - Language.Hawk.NameCheck.Environment
    - Language.Hawk.NameCheck.Error
    - Language.Hawk.NameCheck.State
    - Language.Hawk.Namespace
    
    - Language.Hawk.Parse
    - Language.Hawk.Parse.Error
    - Language.Hawk.Parse.Grammar
    - Language.Hawk.Parse.Helpers
    - Language.Hawk.Parse.Lex
    - Language.Hawk.Parse.Lex.Error
    - Language.Hawk.Parse.Lex.Format
    - Language.Hawk.Parse.Lex.State
    - Language.Hawk.Parse.Message
    - Language.Hawk.Parse.Token

    - Language.Hawk.Syntax
    - Language.Hawk.Syntax.Decl
    - Language.Hawk.Syntax.DataDecl
    - Language.Hawk.Syntax.Expression
    - Language.Hawk.Syntax.Location
    - Language.Hawk.Syntax.Pass
    - Language.Hawk.Syntax.Prim
    - Language.Hawk.Syntax.Type

    # - Language.Hawk.Target.LLVM.Codegen
    # - Language.Hawk.Target.LLVM.Emit
    # - Language.Hawk.Target.LLVM.Types

    - Language.Hawk.TypeCheck
    - Language.Hawk.TypeCheck.Assumption
    - Language.Hawk.TypeCheck.Environment
    - Language.Hawk.TypeCheck.Error
    - Language.Hawk.TypeCheck.Types

    ## Extra, possibly seperate packages or upstream merges
    - Data.Bag
    - Control.Monad.Chronicle.Extra

tests:
  spec:
    source-dirs: test-suite
    main: Spec.hs
    dependencies:
      - base
      - data-default-class
      - hawk
      - tasty
      - tasty-hspec
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

#  doctest:
#    source-dirs: test-suite
#    main: DocTest.hs
#    dependencies:
#      - base
#      - doctest
#      - Glob
#    ghc-options:
#      - -rtsopts
#      - -threaded
#      - -with-rtsopts=-N

#  hlint:
#    source-dirs: test-suite
#    main: HLint.hs
#    dependencies:
#      - base
#      - hlint
#    ghc-options:
#      - -rtsopts
#      - -threaded
#      - -with-rtsopts=-N
    

benchmarks:
  criterion:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
      - base
      - hawk
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
